export type SupportedPlatform =
  | 'youtube'
  | 'instagram'
  | 'facebook'
  | 'twitter'
  | 'tiktok'
  | 'whatsapp'
  | 'vimeo'
  | 'dailymotion'
  | 'twitch'
  | 'reddit'
  | 'pinterest'
  | 'linkedin'
  | 'snapchat'
  | 'likee'
  | 'generic';

export type VideoQualityLabel =
  | '8K'
  | '4K'
  | '2K'
  | '1080p'
  | '720p'
  | '480p'
  | '360p'
  | 'Audio';

export type VideoFormat = 'mp4' | 'mkv' | 'mp3' | 'm4a' | 'ogg' | 'wav' | 'srt';

export type DownloadStatus =
  | 'PENDING'
  | 'ANALYZING'
  | 'QUEUED'
  | 'DOWNLOADING'
  | 'PROCESSING'
  | 'COMPLETED'
  | 'FAILED'
  | 'CANCELLED'
  | 'PAUSED';

export type UserRole = 'USER' | 'ADMIN';

export interface SubtitleTrack {
  language: string;
  code: string;
  name: string;
  isAutoGenerated: boolean;
  url?: string;
}

export interface QualityOption {
  label: VideoQualityLabel;
  height: number;
  available: boolean;
  estimatedBytes?: number;
  formatNote?: string;
  fps?: number;
}

export interface PlaylistItem {
  id: string;
  url: string;
  title: string;
  thumbnailUrl: string;
  durationSec: number;
}

export interface AnalyzeResult {
  url: string;
  urlHash: string;
  platform: SupportedPlatform;
  title: string;
  thumbnailUrl: string;
  durationSec: number;
  uploader: string;
  viewCount?: number;
  isLive: boolean;
  isPlaylist: boolean;
  playlistItems?: PlaylistItem[];
  qualities: QualityOption[];
  formats: VideoFormat[];
  subtitles: SubtitleTrack[];
}

export interface AnalyzeRequest {
  url: string;
}

export interface CreateDownloadRequest {
  url: string;
  quality: VideoQualityLabel;
  format: VideoFormat;
  subtitleLang?: string;
  useCookies?: boolean;
}

export interface DownloadItem {
  id: string;
  userId: string;
  url: string;
  urlHash: string;
  platform: SupportedPlatform;
  title: string;
  thumbnailUrl: string;
  durationSec: number;
  quality: VideoQualityLabel;
  format: VideoFormat;
  status: DownloadStatus;
  progress: number;
  speedBps: number;
  etaSec: number;
  totalBytes: number;
  downloadedBytes: number;
  errorMsg?: string;
  outputPath?: string;
  signedUrl?: string;
  createdAt: string;
  completedAt?: string;
}

export interface ProgressEventPayload {
  type: 'progress' | 'complete' | 'failed' | 'status_change';
  downloadId: string;
  status: DownloadStatus;
  progress: number;
  speedBps: number;
  etaSec: number;
  downloadedBytes: number;
  totalBytes: number;
  errorMsg?: string;
  signedUrl?: string;
}

export interface PublicStats {
  totalDownloads: number;
  supportedSitesCount: number;
  avgSpeedMbps: number;
}

export interface UserProfile {
  id: string;
  email: string;
  name: string;
  role: UserRole;
  planId: string;
  isBanned: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface DmcaSubmissionRequest {
  reporterEmail: string;
  targetUrl: string;
  reason: string;
  infringementProof: string;
  signature: string;
}

export interface AdminOverviewStats {
  totalUsers: number;
  activeNow: number;
  downloadsToday: number;
  bandwidthBytesToday: number;
  errorRatePercent: number;
  queueDepth: number;
  activeWorkers: number;
}

export interface BatchAnalyzeRequest {
  urls: string[];
}

export interface BatchAnalyzeResult {
  results: AnalyzeResult[];
  failed: { url: string; error: string }[];
}

export interface SmartModeConfig {
  enabled: boolean;
  defaultQuality: VideoQualityLabel;
  defaultFormat: VideoFormat;
  defaultSubtitleLang?: string;
}

export interface AuthRegisterRequest {
  email: string;
  password: string;
  name: string;
}

export interface AuthLoginRequest {
  email: string;
  password: string;
}

export interface AuthResponse {
  accessToken: string;
  refreshToken: string;
  user: UserProfile;
}

export interface CookieVaultItem {
  id: string;
  platform: SupportedPlatform;
  hasCookie: boolean;
  updatedAt: string;
}

export interface SaveCookieRequest {
  platform: SupportedPlatform;
  cookieString: string;
}

export interface HistoryQueryParams {
  search?: string;
  platform?: string;
  format?: string;
  page?: number;
  limit?: number;
}
